services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "postgres"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    ports:
      - "5432:5432"
  nginx:
    image: nginx:latest 
    restart: always
    volumes:
      - ./app/api_gateway/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8888:8888"
  # order:
  #   build: 



