name: pet.yaml
run-name: ${{ github.actor }} is running pet workflow
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - run: go build app/pet/cmd/main.go
