name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Docker Build
      run: docker build -t local -f ./Dockerfile .
    - name: Docker Run
      run: docker run -rm local
